Feature: Get token generated by an reusable user
#creating a new user that is reusable for every scenario and getting a new token with it.
  Background:
    * def userName = Java.type('features.support.utils.Utils').generateRandomUsername()
    * def requestBody = read('classpath:features/account/userdata/user-credentials.json')
    * requestBody.userName = userName

    Given url baseUrl

    @setup
    Scenario:
      Given path '/Account/v1/User'
      And request requestBody
      When method post
      Then status 201
      * def userID = response.userID

      Given path '/Account/v1/GenerateToken'
      And request requestBody
      When method post
      Then status 200
      * def token = response.token